### ISSUE TITLE
{fwildclusterboot} (0.13) issues

### ISSUE THREAD

**Issue by patrick-weiss** [s3alfisc/wildrwolf#9]
Running the examples for wildrwolf runs into issues due to the newest version of {fwildclusterboot} (0.13). Seed is no longer accepted as a function input.

The following error message appears:

Error: in boottest.fixest(models[[x]], param = param, B = B...:
 'seed' is not a valid argument of function boottest.fixest.

**Comment by patrick-weiss** [comment]
Found that the issue is already implemented in newer versions.

**Comment by s3alfisc** [comment]
Thanks @patrick-weiss . I actually forgot to merge the changes into main, so it's very good that you reminded me =) You should now also be able to download the package from CRAN, btw!
